# HW 1. numpy tasks

In [7]:
import numpy as np

## Створіть масив NumPy із 10 випадкових цілих чисел. 

Виконайте наступні операції:

- Знайдіть середнє, медіану та стандартне відхилення масиву.
- Замініть всі парні числа у масиві на 0.

In [8]:
arr = np.random.randint(1, 100, size=10)
arr

array([77, 77, 81, 97, 46, 15, 35, 13, 27, 56])

In [9]:
{
    'mean': np.mean(arr),
    'median': np.median(arr),
    'std': np.std(arr)
}

{'mean': 52.4, 'median': 51.0, 'std': 28.23189685444462}

In [10]:
arr[arr % 2 == 0] = 0
arr

array([77, 77, 81, 97,  0, 15, 35, 13, 27,  0])

## Індексація та зрізка в NumPy:

- Створіть 2D масив NumPy (матрицю) розміром (3, 3) із випадковими цілими числами.
- Виведіть перший рядок матриці.
- Виведіть останній стовпець матриці.
- Виведіть діагональні елементи матриці.

In [11]:
matrix = np.random.randint(1, 100, size=(3, 3))
matrix

array([[94, 59, 51],
       [30, 37, 47],
       [51, 98, 94]])

In [12]:
matrix[0]

array([94, 59, 51])

In [13]:
matrix[:, -1]

array([51, 47, 94])

In [15]:
np.diagonal(matrix)

array([94, 37, 94])

### Створіть 2D масив NumPy розміром (3, 3) та 1D масив розміром (3,). Використайте broadcasting для додавання 1D масиву до кожного рядка 2D масиву.

In [16]:
matrix_2d = np.random.randint(1, 10, size=(3, 3))
matrix_2d

array([[1, 2, 3],
       [6, 5, 9],
       [1, 6, 2]])

In [17]:
array_1d = np.array([1, 2, 3])
array_1d

array([1, 2, 3])

In [19]:
matrix_2d + array_1d

array([[ 2,  4,  6],
       [ 7,  7, 12],
       [ 2,  8,  5]])

## Створіть 2D масив NumPy розміром (5, 5) з випадковими цілими числами.

- Знайдіть та виведіть всі унікальні елементи у масиві.
- виведіть всі рядки, сума елементів у яких більша за певне значення. (значення оберіть самі)

In [15]:
matrix = np.random.randint(1, 10, size=(5, 5))
matrix

array([[4, 6, 5, 9, 2],
       [1, 5, 2, 7, 2],
       [4, 6, 7, 3, 4],
       [9, 6, 8, 4, 1],
       [1, 4, 2, 1, 2]])

In [16]:
unique_elements = np.unique(matrix)
unique_elements

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
 matrix[np.sum(matrix, axis=1) > 15]

array([[4, 6, 5, 9, 2],
       [1, 5, 2, 7, 2],
       [4, 6, 7, 3, 4],
       [9, 6, 8, 4, 1]])

### Створіть 1D масив NumPy, що містить цілі числа від 1 до 20 (включно).

- Використайте оператор shape, щоб перетворити 1D масив у 2D масив розміром (4, 5). Переконайтеся, що отриманий перетворений масив має бажаний розмір.

In [34]:
array_1d = np.arange(1, 21)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
array_2d = array_1d.reshape(4, 5)
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [36]:
array_2d.shape

(4, 5)